{% extends "layout.phtml" %}
{% block body %}
	{% include "header.phtml" %}

	<div class="container">
		<div id="alert-container" class="hidden alert" role="alert"></div>
		<div id="game-section" class="row justify-content-center">

		</div>
	</div>

	<script type="template" id="game-ongoing">
		<div id="player-scores-mobile" class="col-lg-4 d-lg-none d-flex flex-row">
			[[each game.players as player on player_score]]
		</div>
		<div id="game-play-section" class="col-lg-8">
			<div id="board-wrapper">
				<ul id="board">
					[[each board as cell on board_cell]]
				</ul>
			</div>
			<div class="game-info">
				Tokens remaining: [[game.size_bag]]
			</div>
			<div id="player-hand">
				[[each player_hand as token on player_token]]
			</div>
			<div id="confirm-button-wrapper">
				<button id="confirm-play" class="btn btn-primary btn-full-width" disabled>Confirm</button>
			</div>
		</div>
		<div id="player-scores" class="col-lg-4 d-none d-lg-block">
			<h3>Scores:</h3>
			[[each game.players as player on player_score]]
		</div>
	</script>

	<script type="template" id="board-token">
		<div class="token" data-value="[[token.value]]">
			[[token.value]]
		</div>
	</script>

	<script type="template" id="player-token">
		<div class="token" id="player-token-[[token.index]]" data-value="[[token.value]]" draggable="true">
			[[token.value]]
		</div>
	</script>

	<script type="template" id="board-cell">
		<li class="cell cell-[[cell.type]]" data-x="[[cell.x]]" data-y="[[cell.y]]">
			[[if cell.token then board_token with cell]]
		</li>
	</script>

	<script type="template" id="game-open">
		Game open
	</script>

	<script type="template" id="game-finished">
		<div id="game-finished-section" class="col-sm-4">

			[[if game.current_is_winner then winner_token]]
			<h1>
				[[game.winner.name]] won!
			</h1>
			<div id="player-scores">
				[[each game.players as player on player_score]]
			</div>
			<a href='/' class="btn btn-primary">Go Back to Game page</a>
		</div>
	</script>

	<script type="template" id="winner-token">
		<div class="image winner"></div>
	</script>

	{% include "game-player-info.phtml" %}
{% endblock %}
{% block scripts %}
	<script type="text/javascript" src="{{ url_for('static', filename='scripts/game.js') }}"></script>
	<script type="text/javascript" src="{{ url_for('static', filename='scripts/modules/game.page.js') }}"></script>
	<script type="text/javascript" src="{{ url_for('static', filename='scripts/modules/header.js') }}"></script>
{% endblock %}
