<!doctype html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
		<title>Three 2 Fifteen</title>
		{% for item in data %}
		<meta id="{{ item.key }}" data-value="{{ item.value }}" />
		{% endfor %}
		<link href="https://fonts.googleapis.com/css?family=PT+Sans:400,400i,700,700i" rel="stylesheet">
		<link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
		<link rel="stylesheet" href="{{ url_for('static', filename='stylesheets/main.css') }}">
	</head>
	<body>
		{% block body %}{% endblock %}
		<script type="text/javascript" src="https://ghislain-rodrigues.fr/js/butterfly.min.js"></script>
		<script type="text/javascript" src="/config.js"></script>
		<script type="text/javascript" src="{{ url_for('static', filename='scripts/utils.js') }}"></script>
		<script type="text/javascript" src="{{ url_for('static', filename='scripts/socket.js') }}"></script>
		<script type="text/javascript" src="{{ url_for('static', filename='scripts/request.js') }}"></script>
		<script type="text/javascript" src="{{ url_for('static', filename='scripts/auth.js') }}"></script>
		<script type="text/javascript" src="{{ url_for('static', filename='scripts/app.js') }}"></script>
		{% block scripts %}{% endblock %}
		<script type="text/javascript" src="{{ url_for('static', filename='scripts/main.js') }}"></script>
	</body>
</html>
