{% extends "layout.phtml" %}
{% block body %}
<div class="container">
	<div class="row align-items-center justify-content-md-center fullscreen">
		<div class="col-sm-4">
			<p>
				Three2Fifteen is a crossword-style game with numbers instead of
				letters. The rules can be found <a href="/rules">here</a>.
			</p>
			<div class="card">
				<div class="card-body">
					<h2>Sign In</h2>
					<form id="login-form" method="POST" action="">
						<div id="form-message"></div>
						<div class="form-group">
							<input type="hidden" name="to" value="{{ to }}" />
							<label for="Username">Username</label>
							<input type="text" name="username" placeholder="Username" class="form-control" id="exampleFormControlInput1" />
						</div>
						<div class="form-group">
							<label for="password">Password</label>
							<input type="password" name="password" placeholder="Password" class="form-control" id="exampleInputPassword1"/>
						</div>
						<input type="submit" class="btn btn-primary btn-full-width" value="Log in" />
					</form>
					<hr/>
					Don't have account?
					<a href="/sign-up">Sign up</a>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}
{% block scripts %}
	<script type="text/javascript" src="{{ url_for('static', filename='scripts/modules/user.login.js') }}"></script>
{% endblock %}
