{% extends "layout.phtml" %}
{% block body %}
<div class="container">
	<div class="row align-items-center justify-content-md-center fullscreen">
		<div class="col-sm-4">
			<div class="card">
				<div class="card-body">
					<h2>Sign Up</h2>
					<form id="signup-form" method="POST" action="">
						<div id="form-message"></div>
						<div class="form-group">
							<label for="name">Name</label>
							<input type="text" id="name" name="name" placeholder="Name" class="form-control" />
						</div>
						<div class="form-group">
							<label for="username">Username</label>
							<input type="text" id="username" name="username" placeholder="Username" class="form-control" />
						</div>
						<div class="form-group">
							<label for="password">Password</label>
							<input type="password" id="password" name="password" placeholder="Password" class="form-control" />
						</div>
						<div class="form-group">
							<label for="password-confirm">Confirm password</label>
							<input type="password" id="password-confirm" name="password-confirm" placeholder="Confirm password" class="form-control" />
						</div>
						<input type="submit" class="btn btn-primary btn-full-width" value="Sign up" />
					</form>
					<hr/>
					Already have account?
					<a href="/login">Sign In</a>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}
{% block scripts %}
	<script type="text/javascript" src="{{ url_for('static', filename='scripts/modules/user.signup.js') }}"></script>
{% endblock %}
