DROP TABLE IF EXISTS app_user;
CREATE TABLE app_user (
	id_user SERIAL PRIMARY KEY,
	username VARCHAR(32) UNIQUE NOT NULL,
	password VARCHAR(128) NOT NULL,
	date_created TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

DROP TABLE IF EXISTS player;
CREATE TABLE player (
	id_player SERIAL PRIMARY KEY,
	id_user INTEGER REFERENCES app_user(id_user) NOT NULL,
	name VARCHAR(128) NOT NULL,
	date_created TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
