DROP TABLE IF EXISTS player;
CREATE TABLE player (
	id_player SERIAL PRIMARY KEY,
	username VARCHAR(32) UNIQUE NOT NULL,
	password VARCHAR(128) NOT NULL,
	name VARCHAR(128) NOT NULL,
	date_created TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
